### ISSUE TITLE
在最大化时取消圆角效果

### ISSUE THREAD

**Issue by hv0905** [BetterNCM/RoundCornerNCM#4]
在双显示器下，若在1显示器下最大化网易云窗口，在2显示器的左边边缘会显示一个突出的圆角，如下图：
![image](https://user-images.githubusercontent.com/29349119/218715820-11f34677-0db3-44c7-b9e1-f48b6d26010c.png)

在窗口最大化后取消圆角，然后取消最大化时恢复圆角应该可以改善这个效果。

**Comment by Sn0r1axi** [comment]
同样有这个问题。。不过betterNCM已经删库跑路，感觉作者也没兴趣维护了

**Comment by Vincy1230** [comment]
戳戳，同问，作者现在还在吗
